spring.application.name=StoredProcedure

server.port=8095

# postgres | mysql | oracle

app.target-db=postgres

trino.api-url=http://localhost:9091/v1/statement

spring.datasource.trino.url=jdbc:trino://localhost:9091/iceberg
spring.datasource.trino.username=adsuser
spring.datasource.trino.catalog=iceberg

spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/Stored_Procedure
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=123456
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

#spring.datasource.postgres.url=jdbc:postgresql://192.168.56.136:5432/Stored_Procedure
#spring.datasource.postgres.username=postgres
#spring.datasource.postgres.password=AdS@3421
#spring.datasource.postgres.driver-class-name=org.postgresql.Driver

spring.datasource.mysql.url=jdbc:mysql://192.168.1.24:3306/Stored_Procedure
spring.datasource.mysql.username=dell
spring.datasource.mysql.password=P3S0luTions!
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.mysql.url=jdbc:mysql://localhost:3306/Stored_Procedure
#spring.datasource.mysql.username=root
#spring.datasource.mysql.password=123456
#spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.oracle.url=jdbc:oracle:thin:@//192.168.1.21:1521/XE
spring.datasource.oracle.username=STORED_PROCEDURE
spring.datasource.oracle.password=123456
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

spring.batch.job.enabled=false
